<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<style type="text/css">
    #loading-wrapper{
        width: 100vw;
        height: 100vh;
        position: fixed;
        top: 0;
        left: 0;
        background: rgba(0,0,0,0.4);
        z-index: 9999;
        display: none;
    }
    #loading-wrapper #loading-bar{
        position: absolute;
        top: 40%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    #loading-wrapper #loading-text{
        position: absolute;
        width: 100%;
        text-align: center;
        color: white;
        top: 60%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    @keyframes ldio-j2ljvik7bcj {
        0% { opacity: 1 }
        100% { opacity: 0 }
    }
    .ldio-j2ljvik7bcj div {
        left: 81.175px;
        top: 12.415px;
        position: absolute;
        animation: ldio-j2ljvik7bcj linear 1s infinite;
        background: #ff6200;
        width: 28.65px;
        height: 28.65px;
        border-radius: 14.325px / 14.325px;
        transform-origin: 14.325px 83.085px;
    }.ldio-j2ljvik7bcj div:nth-child(1) {
         transform: rotate(0deg);
         animation-delay: -0.9166666666666666s;
         background: #ff6200;
     }.ldio-j2ljvik7bcj div:nth-child(2) {
          transform: rotate(30deg);
          animation-delay: -0.8333333333333334s;
          background: #ff6200;
      }.ldio-j2ljvik7bcj div:nth-child(3) {
           transform: rotate(60deg);
           animation-delay: -0.75s;
           background: #ff6200;
       }.ldio-j2ljvik7bcj div:nth-child(4) {
            transform: rotate(90deg);
            animation-delay: -0.6666666666666666s;
            background: #ff6200;
        }.ldio-j2ljvik7bcj div:nth-child(5) {
             transform: rotate(120deg);
             animation-delay: -0.5833333333333334s;
             background: #ff6200;
         }.ldio-j2ljvik7bcj div:nth-child(6) {
              transform: rotate(150deg);
              animation-delay: -0.5s;
              background: #ff6200;
          }.ldio-j2ljvik7bcj div:nth-child(7) {
               transform: rotate(180deg);
               animation-delay: -0.4166666666666667s;
               background: #ff6200;
           }.ldio-j2ljvik7bcj div:nth-child(8) {
                transform: rotate(210deg);
                animation-delay: -0.3333333333333333s;
                background: #ff6200;
            }.ldio-j2ljvik7bcj div:nth-child(9) {
                 transform: rotate(240deg);
                 animation-delay: -0.25s;
                 background: #ff6200;
             }.ldio-j2ljvik7bcj div:nth-child(10) {
                  transform: rotate(270deg);
                  animation-delay: -0.16666666666666666s;
                  background: #ff6200;
              }.ldio-j2ljvik7bcj div:nth-child(11) {
                   transform: rotate(300deg);
                   animation-delay: -0.08333333333333333s;
                   background: #ff6200;
               }.ldio-j2ljvik7bcj div:nth-child(12) {
                    transform: rotate(330deg);
                    animation-delay: 0s;
                    background: #ff6200;
                }
    .loadingio-spinner-spinner-ek2ukf9zas4 {
        width: 191px;
        height: 191px;
        display: inline-block;
        overflow: hidden;
        background: transparent;
    }
    .ldio-j2ljvik7bcj {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
    }
    .ldio-j2ljvik7bcj div { box-sizing: content-box; }
    /* generated by https://loading.io/ */
</style>
<div id="loading-wrapper">
    <div class="loadingio-spinner-spinner-ek2ukf9zas4" id="loading-bar"><div class="ldio-j2ljvik7bcj">
        <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
    </div></div>
    <p id="loading-text">로딩 중입니다. 잠시만 기다려 주세요.</p>
</div>
<script>
    const loadingWrapper = document.getElementById('loading-wrapper');
    const loadingText = document.getElementById('loading-text');
    function loaderShow(){
        loadingWrapper.style.display='block';
    }
    function loaderHide(){
        loadingWrapper.style.display='none';
    }
    function loaderTextChange(text){
        loadingText.innerText=text;
    }
</script>